# -*- coding: utf-8 -*-
"""week2_numpy_basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KivJolz60XFLtFPMDWzYsJ9HI3ZnEeK
"""

# Week 2 - NumPy Fundamentals


import numpy as np

# ==========================================
# 1. ARRAY CREATION
# ==========================================

# Basic array
salaries = np.array([30000, 45000, 52000, 38000, 61000])
print("Salaries:", salaries)
print("With 10% bonus:", salaries * 1.10)

# Array shortcuts
print("\nZeros:", np.zeros(5))
print("Ones:", np.ones(5))
print("Range:", np.arange(0, 20, 2))
print("Random:", np.random.rand(5))

# ==========================================
# 2. ARRAY PROPERTIES
# ==========================================

marks = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [70, 75, 80]
])

print("\nArray:\n", marks)
print("Shape:", marks.shape)
print("Dtype:", marks.dtype)
print("Ndim:", marks.ndim)
print("Size:", marks.size)
print("Itemsize:", marks.itemsize, "bytes")

# ==========================================
# 3. INDEXING & SLICING
# ==========================================

runs = np.array([45, 67, 89, 23, 56, 78, 90, 34])

print("\nFirst 3:", runs[:3])
print("Last 3:", runs[-3:])
print("Middle:", runs[2:5])

# 2D slicing
print("\nFirst row:", marks[0, :])
print("First column:", marks[:, 0])
print("Top right 2x2:\n", marks[0:2, 1:3])

# ==========================================
# 4. BOOLEAN INDEXING
# ==========================================

scores = np.array([45, 67, 89, 23, 56, 78, 90, 34])
print("\nScores above 60:", scores[scores > 60])
print("Scores below 40:", scores[scores < 40])

# ==========================================
# 5. USEFUL OPERATIONS
# ==========================================

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("\nSorted:", np.sort(arr))
print("Unique:", np.unique(arr))
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Axis operations
student_marks = np.array([
    [78, 85, 92, 70, 88],
    [82, 79, 95, 68, 91],
    [75, 88, 80, 72, 85]
])

print("\nAverage per student:", np.mean(student_marks, axis=0).round(2))
print("Average per subject:", np.mean(student_marks, axis=1).round(2))

# ==========================================
# 6. RESHAPE
# ==========================================

arr = np.arange(1, 13)
print("\nOriginal:", arr)
print("Reshaped to 3x4:\n", arr.reshape(3, 4))