# -*- coding: utf-8 -*-
"""week2_statistics_basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGKQSsZ1nCJGvPLD2OJMRjl6I6xCefab
"""

# Week 2 - Statistics Fundamentals

import numpy as np

# ==========================================
# 1. DESCRIPTIVE STATISTICS
# ==========================================

temperatures = np.array([28, 32, 35, 30, 29, 33, 31])

print("temperatures:", temperatures)
print("Mean:", np.mean(temperatures).round(2))
print("Median:", np.median(temperatures))
print("Max:", temperatures.max())
print("Min:", temperatures.min())
print("Std Deviation:", np.std(temperatures).round(2))

# ==========================================
# 2. MEAN VS MEDIAN — OUTLIER EFFECT
# ==========================================

salaries = np.array([25000, 28000, 32000, 150000, 29000, 31000, 27000])

print("\nSalaries:", salaries)
print("Mean:", np.mean(salaries).round(2))
print("Median:", np.median(salaries))
print("Std Deviation:", np.std(salaries).round(2))
print("\nMedian represents team better!")
print("150000 pulls mean up unfairly.")

# ==========================================
# 3. VARIANCE & STANDARD DEVIATION
# ==========================================

rohit = np.array([45, 50, 55, 48, 52])
dhoni = np.array([10, 90, 5, 95, 50])

print("\nRohit std:", np.std(rohit).round(2))
print("Dhoni std:", np.std(dhoni).round(2))
print("Rohit is more consistent — lower std deviation!")

# ==========================================
# 4. Z-SCORES
# ==========================================

salaries = np.array([25000, 28000, 32000, 150000, 29000, 31000, 27000])

mean = np.mean(salaries)
std = np.std(salaries)
z_scores = (salaries - mean) / std

print("\nZ-scores:", z_scores.round(2))
print("Z-score of 150000:", z_scores[3].round(2))
print("150000 is an outlier — beyond 2 standard deviations!")

# ==========================================
# 5. NORMAL DISTRIBUTION — 68-95-99 RULE
# ==========================================

numbers = np.random.normal(100, 15, 500)

print("\nMean:", np.mean(numbers).round(2))
print("Std:", np.std(numbers).round(2))

within_1std = np.sum((numbers >= 85) & (numbers <= 115))
within_2std = np.sum((numbers >= 70) & (numbers <= 130))
within_3std = np.sum((numbers >= 55) & (numbers <= 155))

print("\n68-95-99 Rule Verification:")
print(f"Within 1 std (expect ~340): {within_1std}")
print(f"Within 2 std (expect ~475): {within_2std}")
print(f"Within 3 std (expect ~499): {within_3std}")